### ISSUE TITLE
バッチファイルが同梱されていない

### ISSUE THREAD

**Issue by istallia** [662611034/psd_fairu_no_reiyaa_no_namae_no_mae_ni_bikkuri_maaku_ya_asutarisuku_wo_ikkatsu_de_tsukeru_puroguramu#4]
お久しぶりです。
本題について認知はしていたのですが、「まあいいか」と放置してしまっていました。(何名か私の方で直接案内しました)

本題ですが、Releaseのzipファイルに`regist.bat`と`remove.bat`も同梱していただけると助かります。これを管理者権限で実行すると右クリックメニューからPSDファイルを開けるようになります。
作業としては

1. `regist.bat`内のexeファイルの名前に付いているバージョンを合うように書き換え
2. 3つのファイルをまとめてzipにする

だけです。バッチファイルはShift-JISまたはcp932を維持するようお願いします。
よろしくお願いします。

**Comment by 662611034** [comment]
ご連絡ありがとうございます。
この頃.psdファイルのレイヤーの名前の前に「!」や「*」を一括でつけるプログラムを触ることがなくなって全く気付いていませんでした。
最新のreleaseの添付zipを修正しました。

**Comment by istallia** [comment]
確認しました。お早い対応ありがとうございます。
その上で申し訳ないのですが、バッチファイルが実行できませんでしたので、同梱のバッチファイルの改行コードをLFからCRLFに変換してくださいますようお願いいたします。
私の環境のGit for Windowsの設定はコミット時にLFに自動変換するようになっており、cmdがLF単体を改行と認識してくれないためこうなったようです。よもやこんな落とし穴があろうとは思いませんでした……。

**Comment by 662611034** [comment]
（バッチファイル何も分からなくてちゃんと動いてないのにアップロード下の画ばれてしまった……）
ちゃんとこちらで動作確認せずにアップロードしてすみませんでした。
改めて動作確認した上で新しくアップロードしたのでご確認をお願いします。

**Comment by istallia** [comment]
こちらでも正常な動作を確認しましたので本Issueを閉じます。
ご対応ありがとうございました。
